f = open('/root/market-analyzer-bot/docker-compose.yml', 'r')
c = f.read()
f.close()
c = c.replace('#- "5432:5432"', '')
c = c.replace('#- "6379:6379"', '')
f = open('/root/market-analyzer-bot/docker-compose.yml', 'w')
f.write(c)
f.close()
print('OK')
